apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: challenges
  name: challenges
spec:
  type: NodePort
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: challenges
status:
  loadBalancer: {}
