apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: challenges
  name: challenges
spec:
  containers:
  - image: localhost:5000/challenges
    name: challenges
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
